# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5          # number of pages in the sliding pagination
    default_options:
        page_name: page    # page query parameter name
        sort_field_name: sort  # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true     # ensures distinct results, useful when ORM queries include joins
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'  # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template